image: rikorose/gcc-cmake

before_script:
  - apt-get update -qq && apt-get install libboost-iostreams-dev -y

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DLIBNBTPP_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release
    - make
  artifacts:
    paths:
      - build/libnbtpp.so
      - build/nbtpptest
      - binary.hpp
      - endianness.hpp
      - nbtfile.hpp
      - nbtpp.hpp

test:
  stage: test
  script:
    - ls
    - cd build
    - ls
    - chmod +x nbtpptest
    - ./nbtpptest
  dependencies:
    - build