image: rikorose/gcc-cmake:8

before_script:
  - apt-get update -qq && install libboost-all-dev

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake .. -DLIBNBTPP_BUILD_TESTS=ON
    - make
  artifacts:
    paths:
      - build/libnbtpp.so

test:
  stage: test
  script:
    - ./build/nbtpptest