build:
  stage: build
  image: rikorose/gcc-cmake
  before_script:
    - apt-get update -qq && apt-get install libboost-iostreams-dev zlib1g-dev -y
  script:
    - mkdir build
    - cd build
    - cmake .. -DLIBNBTPP_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release
    - make
    - strip libnbtpp.so
    - strip nbtpptest
  artifacts:
    paths:
      - build/libnbtpp.so
      - build/nbtpptest
      - binary.hpp
      - endianness.hpp
      - nbtfile.hpp
      - nbtpp.hpp

test:
  image: busybox
  stage: test
  script:
    - cd build
    - chmod +x nbtpptest
    - ./nbtpptest
  dependencies:
    - build