build:
  stage: build
  image: base/devel
  before_script:
    - pacman -Sy cmake boost zlib ninja --noconfirm
  script:
    - mkdir build
    - cd build
    - cmake .. -DLIBNBTPP_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release -G Ninja
    - ninja
    - strip libnbtpp.so
    - strip nbtpptest
  artifacts:
    paths:
      - build/libnbtpp.so
      - build/nbtpptest
      - binary.hpp
      - endianness.hpp
      - nbtfile.hpp
      - nbtpp.hpp

test:
  image: base/devel
  stage: test
  script:
    - cd build
    - chmod +x nbtpptest
    - ./nbtpptest
  dependencies:
    - build